let BASEURL = process.env.BASEURL;
let AXIOS_BASEURL = process.env.AXIOS_BASEURL;
let GOOGLE_MAP_KEY = process.env.GOOGLE_MAP_KEY;
let FACEBOOK_APP_ID = process.env.FACEBOOK_APP_ID;
let GOOGLE_CLIENT_ID_OAUTH = process.env.GOOGLE_CLIENT_ID_OAUTH;

export {
  BASEURL,
  AXIOS_BASEURL,
  GOOGLE_MAP_KEY,
  FACEBOOK_APP_ID,
  GOOGLE_CLIENT_ID_OAUTH,
};